title: How to Contribute to SkilledUp Academy Programs
version: 0.0.1
description:
  "Learn how you can improve the quality of SkilledUp Academy's Programs, Challenges, and Activities, by becoming part of the
  discussion.  Open issues, propose improvements, and more."
price: 200
start_date:
end_date:
hours_per_week: 2
weeks: 1
